name: Deploy to Namecheap Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build:static
    
    - name: Deploy to Namecheap via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.NAMECHEAP_FTP_SERVER }}
        username: ${{ secrets.NAMECHEAP_FTP_USERNAME }}
        password: ${{ secrets.NAMECHEAP_FTP_PASSWORD }}
        local-dir: ./dist/portflio/browser/
        server-dir: public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
